### ISSUE TITLE
Hidden Switcher Option

### ISSUE THREAD

**Issue by whjvenyl** [lorenzolewis/starlight-utils#13]
Instead of displaying a tabbed list with multiple sidebars, only display one.
To be used with the new NavLinks option.

Basically this would replace the need, to override the sidebar component in the following example:
![CleanShot 2024-05-28 at 5  03 38](https://github.com/lorenzolewis/starlight-utils/assets/1174049/c0e802e3-dfbb-4753-a7e0-e8b698520699)
![CleanShot 2024-05-28 at 5  05 17](https://github.com/lorenzolewis/starlight-utils/assets/1174049/9b464db4-674f-419b-acdc-515a58a4c3a1)
![CleanShot 2024-05-28 at 5  05 31](https://github.com/lorenzolewis/starlight-utils/assets/1174049/ad088de3-9a48-4136-8325-bb4fe0602784)

**Comment by lorenzolewis** [comment]
This is an awesome idea! I would like to fiddle around with the nav links a bit first because they don't render well on Mobile at all. But this is on my list to tackle after that.

**Comment by andrii-bodnar** [comment]
Thanks for the great library! I am also looking for this feature, it would be useful to have a possibility to hide switcher in case of using nav links.

**Comment by lorenzolewis** [comment]
If anyone would like to create a PR for this then I would be happy to accept it. I would imagine exposing an additional `switcherStyle` of `hidden` in the Starlight Utils config that would simply not render any switcher.

**Comment by andrii-bodnar** [comment]
Hello, I just created the PR: #48

**Comment by lorenzolewis** [comment]
Hi! This has just been released thanks to @andrii-bodnar 🎉 

https://github.com/lorenzolewis/starlight-utils/releases/tag/%40lorenzo_lewis%2Fstarlight-utils%400.1.2
