### ISSUE TITLE
Conflict with starlight-blog plugin

### ISSUE THREAD

**Issue by gdisk** [lorenzolewis/starlight-utils#132]
hello，i  want to use this plugin with starlight-blog plugin at the same time,  but when i use them together, it seems  can not work correctly。codes like below：

```js
// astro.config.mjs
import starlightUtils from "@lorenzo_lewis/starlight-utils";
import starlightBlog from 'starlight-blog'

const starlightBlogPlugin = starlightBlog({
  title: "My Blog",
  prefix: "blogs",
  postCount: 10, 
  recentPostCount: 10, 
  authors: {
    authors1: {
      name: "authors1"
    },
    authors2: {
      name: "authors2",
    },
  }
});

const starlightUtilsPlugin = starlightUtils({
  multiSidebar: {
    switcherStyle: "dropdown",
  }
});

export default defineConfig({
  ...
  integrations: [
      starlight({
        ...
        plugins: [
          starlightImageZoom(),
          starlightUtilsPlugin,
          starlightBlogPlugin,
        ],
     })
  ]
```

bug details:

1. when plugins config use starlightBlogPlugin before starlightUtilsPlugin , multiSidebar can not work, all sidebas while show;
2. when plugins config use starlightUtilsPlugin before starlightBlogPlugin , and visit /blogs, the sidebar is the first item in configured sidebar, and not the sidebar generated by starlightBlogPlugin.

can you help me?  so  thanks!

**Comment by HiDeoo** [comment]
Small note that I answered the opposite question in https://github.com/HiDeoo/starlight-blog/issues/95#issuecomment-2495530232

**Comment by gdisk** [comment]
thanks
