### ISSUE TITLE
Nav Links will only display the highlighted style for the exact page

### ISSUE THREAD

**Issue by andrii-bodnar** [lorenzolewis/starlight-utils#43]
Hello,

Nav Links will only display the highlighted style for the current page. When navigating to other pages, the font weight is reset to the default.

https://github.com/lorenzolewis/starlight-utils/assets/29282228/788ad3a2-ea51-4e37-8db6-b9f8deb97791

**Comment by lorenzolewis** [comment]
Hi! This is expected as it's using a similar mechanism to that which Starlight uses for sidebars. There's an upstream discussion in Starlight about a similar item (https://github.com/withastro/starlight/discussions/950)

I would want this functionality to be implemented directly in Starlight before adding it inside of Starlight Utils.

**Comment by andrii-bodnar** [comment]
Thank you! I was able to achieve the desired functionality by setting `id` attributes for my navbar items:

```js
{
  label: "leading",
  items: [
    { label: "Docs", link: "/docs", attrs: { id: "docs-nav-button" } },
    { label: "Demos", link: "/demos/1", attrs: { id: "demos-nav-button" } },
  ],
}
```

And then by applying custom CSS to those IDs according to my custom highlight logic.
