### ISSUE TITLE
specifying multisidebar tab labels

### ISSUE THREAD

**Issue by quickfold** [lorenzolewis/starlight-utils#54]
Hi, very interested to use multisidebar but don't see how to configure the sidebars other than how to set set the selection style. I read https://starlight-utils.pages.dev/utilities/multi-sidebar/ but I don't see how to label the tabs in the multisidebar or how to set the links within each sidebar tab. The example config file doesn't include tab labels "main" or "demo". Is the multisidebar navigation automatically built based on a folder structure? Or is there something I'm missing? Thanks.

**Comment by lorenzolewis** [comment]
Hi, @quickfold ! MultiSidebar uses the native Starlight sidebar functionality and builds on top of that. More can be found here: https://starlight.astro.build/guides/sidebar/

Essentially you just use the existing Starlight sidebar config and it builds from there. 

That being said, I agree that it could be more clear in the docs on my side. Would you be interested in submitting a PR to the page you linked to make it more clear?

**Comment by quickfold** [comment]
I'm happy to contribute documentation of you can provide corrections/guidance. However, I can't use Git, so it's only possible if there's a way to get them to you via email (couldn't find your email address) or posting it somewhere.

I assume that `main`and `demo` are the only two folders under `src/content/docs`; is that correct? If so, is there any way to exclude a folder at the same level as `main` and `demo` from being included in the tabs?

Re: docs, I'm speaking as a real beginner/novice. For me, since you use the starlight-utils site itself to demo your utilities, I'd find it very helpful if the site sidebar included a section that showed the file tree structure of the site as well as the text of relevant config pages (or downloadable files I could compare to rendered site).

**Comment by lorenzolewis** [comment]
I just updated the site to include an edit link. So if you go to the bottom of the page you should now see it (may need to refresh). 

If you're able to use GitHub logged in then you can directly clone, edit, and propose the changes all through that one link. Let me know if there are any issues or that doesn't work for you. 

As for the content of any changes, I think updating the code snippet in the page you originally linked to also include the sidebar config would be a good improvement. 

As for explaining the structure of files etc. I would prefer to link directly to the Starlight docs as it is exactly the same, Starlight Utils doesn't really do anything special there and relies 100% on Starlight logic and how it's documented to work. 

Hopefully that all makes sense and let me know if you encounter any issues!

**Comment by quickfold** [comment]
OK, I added to the docs and tried to create a pull request--let me know if it worked.

**Comment by lorenzolewis** [comment]
Perfect! I saw it come through so I'll take a look at it a bit later. I'll put any additional commends directly in the PR. 

Thanks!

**Comment by quickfold** [comment]
I got a message from changebot asking me to add a changeset, and I don't have time right now to figure out the instructions for that (I was barely able to do a pull request for the first time). Do I have to do the changeset for you to check my changes?

**Comment by lorenzolewis** [comment]
Well firstly, congrats on submitting your first pull request 😉

The change set is only required if there are code changes, not for documentation changes, no not needed for that PR and nothing to worry about. 

I haven't had time to sit down and review it will do it as soon as I have the time. 

Thanks!

**Comment by lorenzolewis** [comment]
Just got #57 merged in. Thanks again for your feedback and PR on this, @quickfold !
